"use client";
import Image from "next/image";
import Link from "next/link";
import { Clock3,Crown,LoaderCircle } from "lucide-react";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { FOOD_EMOJIS,FOODS,type Food,type PreferenceToken } from "@/lib/game/rules";
import { getAnonymousAccessToken,getSupabaseBrowserClient } from "@/lib/supabase/browser";
type Room={id:string;join_code:string;timer_seconds:number;status:string};type Player={id:string;user_id:string;nickname:string;seat:number;score?:number;is_host:boolean};type Game={id:string;state_version:number;status:string};type Round={id:string;number:number;cat_id:number;starter_seat:number;active_seat:number;phase:"plating"|"stealing"|"round_result"|"finished";cycle:number;deadline:string;steals_taken:number};type Card={id:string;food:Food;player_id:string};type Cat={id:number;name:string;points:number;preference_tokens:PreferenceToken[]};const LABELS:Record<Food,string>={chicken:"Chicken",milk:"Milk",fish:"Fish",croquettes:"Croquettes"};
export function GameTable({room,players:initialPlayers,userId,code}:{room:Room;players:Player[];userId?:string;code:string}){
 const [game,setGame]=useState<Game>();const [round,setRound]=useState<Round>();const [cat,setCat]=useState<Cat>();const [players,setPlayers]=useState(initialPlayers);const [hand,setHand]=useState<Card[]>([]);const [plates,setPlates]=useState<Card[]>([]);const [selected,setSelected]=useState<string[]>([]);const [target,setTarget]=useState<string>();const [now,setNow]=useState(0);const [busy,setBusy]=useState(false);const [shakingSeat,setShakingSeat]=useState<number>();const previousActiveSeat=useRef<number | undefined>(undefined);const supabase=getSupabaseBrowserClient();const activeSeat=round?.active_seat;const me=players.find(p=>p.id===hand[0]?.player_id)??players.find(p=>p.user_id===userId);const active=players.find(p=>p.seat===activeSeat);const myTurn=me?.seat===activeSeat;
 const load=useCallback(async()=>{const {data:g}=await supabase.from("games").select("id,state_version,status").eq("room_id",room.id).order("started_at",{ascending:false}).limit(1).single();if(!g)return;setGame(g as Game);const [{data:r},{data:p}]=await Promise.all([supabase.from("rounds").select("id,number,cat_id,starter_seat,active_seat,phase,cycle,deadline,steals_taken").eq("game_id",g.id).order("number",{ascending:false}).limit(1).single(),supabase.from("players").select("id,user_id,nickname,seat,score,is_host").eq("room_id",room.id).is("left_at",null).order("seat")]);setPlayers((p??[]) as Player[]);if(!r)return;setRound(r as Round);const [{data:c},{data:h},{data:pc}]=await Promise.all([supabase.from("cat_definitions").select("id,name,points,preference_tokens").eq("id",r.cat_id).single(),supabase.from("hand_cards").select("id,food,player_id").eq("round_id",r.id),supabase.from("plate_cards").select("id,food,player_id").eq("round_id",r.id)]);setCat(c as Cat);setHand((h??[]) as Card[]);setPlates((pc??[]) as Card[]);},[room.id,supabase]);
 useEffect(()=>{const refresh=()=>{setNow(Date.now());void load();};const initial=window.setTimeout(refresh,0);const timer=window.setInterval(refresh,2000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};},[load]);const seconds=Math.max(0,Math.ceil((new Date(round?.deadline??0).getTime()-now)/1000));
 useEffect(()=>{if(activeSeat===undefined)return;const previous=previousActiveSeat.current;previousActiveSeat.current=activeSeat;if(previous===undefined||previous===activeSeat)return;setShakingSeat(activeSeat);const timer=window.setTimeout(()=>setShakingSeat(undefined),700);return()=>window.clearTimeout(timer);},[activeSeat]);
 useEffect(()=>{if(seconds!==0||!game)return;const timer=window.setTimeout(()=>{void(async()=>{const token=await getAnonymousAccessToken();await fetch("/api/game",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({command:"advance",gameId:game.id,expectedVersion:game.state_version,idempotencyKey:crypto.randomUUID()})});await load();})();},0);return()=>window.clearTimeout(timer);},[seconds,game,load]);
 async function command(kind:"plate"|"pass"|"steal"|"finish_steal"){if(!game)return;setBusy(true);const token=await getAnonymousAccessToken();const response=await fetch("/api/game",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({command:"action",gameId:game.id,kind,cardIds:selected,targetCard:target??null,expectedVersion:game.state_version,idempotencyKey:crypto.randomUUID()})});setBusy(false);if(response.ok){setSelected([]);setTarget(undefined);await load();}}
 function toggle(card:Card){setSelected(current=>current.includes(card.id)?current.filter(id=>id!==card.id):round?.phase==="plating"?(current.length&&hand.find(c=>c.id===current[0])?.food!==card.food?[card.id]:[...current,card.id]):[...current.slice(-1),card.id]);}const selectedCards=useMemo(()=>hand.filter(c=>selected.includes(c.id)),[hand,selected]);
 if(!game||!round||!cat)return <main className="game-page loading"><LoaderCircle className="animate-spin"/><p>Dealing the cards…</p></main>;
 if(game.status==="finished")return <main className="game-page"><section className="result-card"><p className="eyebrow">The feast is over</p><h1 className="font-display text-5xl font-black">Final standings</h1>{[...players].sort((a,b)=>(b.score??0)-(a.score??0)).map(p=><div className="standing" key={p.id}><strong>#{1+players.filter(q=>(q.score??0)>(p.score??0)).length} {p.nickname}</strong><span>{p.score} pts</span></div>)}<Link className="primary-button mt-6" href="/">Leave room</Link></section></main>;
 return <main className="game-page"><header className="game-header"><Link href="/" className="brand-mark"><span className="brand-paw">✦</span>Regular Kitties</Link><div className="turn-chip"><Clock3 size={16}/><strong>{seconds}s</strong><span>{active?.nickname}&apos;s {round.phase} turn</span></div><span className="room-mini">Room {code}</span></header><div className="table-grid"><aside className="score-panel"><p className="eyebrow">Round {round.number} · Cycle {round.cycle}</p>{players.map(p=><div key={p.id} className={`score-row ${p.id===active?.id?"active":""}`}><span className={`player-avatar ${p.seat===shakingSeat?"turn-shake":""}`}>{p.nickname[0]}</span><span><strong>{p.nickname}</strong><small>{p.seat===round.starter_seat?"Starts this cat":"Seat "+p.seat}</small></span><b>{p.score??0}</b>{p.is_host&&<Crown size={14}/>}</div>)}</aside><section className="cat-table"><div className="cat-card"><Image src="/cat-placeholder.png" alt={cat.name} width={250} height={350}/><div><p className="eyebrow">{cat.points} point cat</p><h1 className="font-display text-4xl font-black">{cat.name}</h1><div className="preference">{cat.preference_tokens.map((token,index)=><PreferenceTokenDisplay key={`${token}-${index}`} token={token}/>)}</div></div></div><div className="plates">{players.map(p=><div key={p.id} className={`plate ${p.id===active?.id?"active":""}`}><strong>{p.nickname}&apos;s plate</strong><div>{plates.filter(c=>c.player_id===p.id).map(c=><FoodCard key={c.id} card={c} selected={target===c.id} onClick={()=>p.id!==me?.id&&setTarget(c.id)}/>)}</div></div>)}</div></section><aside className="log-panel"><h2 className="font-display text-2xl font-bold">How to play</h2><p>{round.phase==="plating"?"Choose any number of one food, or pass.":"Select two matching cards and an opponent’s plated card. Steal up to twice, then finish."}</p><p className="mt-4"><strong>{myTurn?"Your turn.":`Waiting for ${active?.nickname}.`}</strong></p></aside></div><section className="hand-dock"><div className="hand-title"><span><small>Your hand</small><strong>{selected.length?`${selected.length} selected`:"Choose cards"}</strong></span><div className="hand-actions"><button disabled={!myTurn||busy} onClick={()=>void command(round.phase==="plating"?"pass":"finish_steal")}>{round.phase==="plating"?"Pass":"Finish stealing"}</button>{round.phase==="plating"?<button className="primary-button" disabled={!myTurn||!selected.length||busy} onClick={()=>void command("plate")}>Plate selected</button>:<button className="primary-button" disabled={!myTurn||selectedCards.length!==2||selectedCards[0]?.food!==selectedCards[1]?.food||!target||busy} onClick={()=>void command("steal")}>Steal card</button>}</div></div><div className="hand-cards">{hand.map(card=><FoodCard key={card.id} card={card} selected={selected.includes(card.id)} onClick={()=>toggle(card)}/>)}</div></section></main>;
}
function PreferenceTokenDisplay({token}:{token:PreferenceToken}){if(FOODS.includes(token as Food)){const food=token as Food;return <span className="token" role="img" aria-label={LABELS[food]}>{FOOD_EMOJIS[food]}</span>}return <span className="operator">{token}</span>}
function FoodCard({card,selected,onClick}:{card:Card;selected:boolean;onClick:()=>void}){return <button type="button" aria-pressed={selected} onClick={e=>{e.stopPropagation();onClick();}} className={`food-card ${selected?"selected":""}`}><Image src={`/foods/${card.food}.png`} alt="" width={84} height={84}/><span>{LABELS[card.food]}</span></button>}
